// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package simple

import (
	"github.com/google/wire"
)

// Injectors from injector.go:

func InitializeService(isError bool) (*SampleService, error) {
	sampleRepository := NewSampleRepository(isError)
	sampleService, err := NewSampleService(sampleRepository)
	if err != nil {
		return nil, err
	}
	return sampleService, nil
}

func InitializeDatabaseRepository() *DatabaseRepository {
	databasePostgreeSql := NewDatabasePostgreSQL()
	databaseMySql := NewDatabaseMySQL()
	databaseRepository := NewDatabase(databasePostgreeSql, databaseMySql)
	return databaseRepository
}

func InitializeUserProfileService() *UserProfileService {
	userRepository := NewUserRepository()
	userService := NewUserService(userRepository)
	profileRepository := NewProfileRepository()
	profileService := NewProfileService(profileRepository)
	userProfileService := NewUserProfileService(userService, profileService)
	return userProfileService
}

func InitializeDashboardService() *DashboardService {
	showDashboardImpl := NewShowDashboardImpl()
	dashboardService := NewDashboardService(showDashboardImpl)
	return dashboardService
}

// injector.go:

var userSet = wire.NewSet(NewUserRepository, NewUserService)

var profileSet = wire.NewSet(NewProfileRepository, NewProfileService)

var dashboardSet = wire.NewSet(
	NewShowDashboardImpl, wire.Bind(new(ShowDashboard), new(*ShowDashboardImpl)),
)
